CREATE TABLE CLIENTE (
	ID INTEGER PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(100),
	CPF VARCHAR(11)
);

CREATE TABLE PRODUTO (
	ID INTEGER PRIMARY KEY AUTO_INCREMENT,
	DESCRICAO VARCHAR(100),
	PRECO_UNITARIO NUMERIC(20,2)
);

CREATE TABLE PEDIDO (
	ID INTEGER PRIMARY KEY AUTO_INCREMENT,
	CLIENTE_ID INTEGER REFERENCES CLIENTE (ID),
	DATA_PEDIDO TIMESTAMP,
	STATUS VARCHAR(20),
	TOTAL NUMERIC(20,2)
);

CREATE TABLE ITEM_PEDIDO (
	ID INTEGER PRIMARY KEY AUTO_INCREMENT,
	PEDIDO_ID INTEGER REFERENCES PEDIDO (ID),
	PRODUTO_ID INTEGER REFERENCES PRODUTO (ID),
	QUANTIDADE INTEGER
);

insert into cliente values (2, '12345678912', 'Lucas Lucco')

insert into produto values(1, 'caneta', 4.99)

insert into item_pedido values(1, 5, 1, 1)

insert into pedido values(1, now(), 10.00, 1)